SRC_FILES := __fpclassify.c __fpclassifyl.c __math_divzero.c __math_divzerof.c __math_invalid.c __math_invalidf.c __math_oflow.c __math_oflowf.c __math_uflow.c __math_uflowf.c __math_xflow.c __math_xflowf.c 
SRC_FILES += __signbit.c __signbitl.c copysign.c copysignl.c
SRC_FILES += exp_data.c fabs.c fabsl.c floor.c fmod.c fmodl.c frexp.c frexpl.c log_data.c log.c 
SRC_FILES += pow_data.c pow.c round.c scalbn.c scalbnl.c sqrt.c
SRC_FILES += ceil.c ceilf.c ceill.c rint.c rintf.c rintl.c

# SRC_DIR := arm

include $(KERNEL_ROOT)/compiler.mk