SRC_DIR := 
MUSL_DIR :=

SRC_DIR += ctype env errno exit internal
SRC_DIR += locale malloc math misc multibyte network prng regex
SRC_DIR += stdio stdlib string time

MUSL_DIR += ctype env errno exit internal
MUSL_DIR += locale malloc math misc multibyte network prng regex
MUSL_DIR += stdio stdlib string time

include $(KERNEL_ROOT)/compiler.mk