from building import *

cwd     = GetCurrentDir()
src     = [
    'main.c'
]
CPPPATH = [cwd]

## 设置 lcd_test.c 的依赖宏
if GetDepend('BSP_USING_LCD'):
    src += ['lcd_test.c']

## 设置 tcp_client.c 和 tcp_server.c 的依赖宏
if GetDepend('PKG_USING_WIZNET'):
    src += ['tcp_client.c']
    src += ['tcp_server.c']

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

Return('group')



