SRC_FILES := memchr.c memcmp.c memcpy.c memmove.c memrchr.c memset.c stpcpy.c stpncpy.c
SRC_FILES += strcasecmp.c strcat.c strchr.c strchrnul.c strcmp.c strcpy.c strcspn.c strdup.c strlen.c 
SRC_FILES += strncasecmp.c strncat.c strncmp.c strncpy.c strnlen.c strrchr.c strspn.c strstr.c 
SRC_FILES += strtok_r.c strtok.c wcschr.c wcslen.c 



include $(KERNEL_ROOT)/compiler.mk