import os
from building import *

cwd  = GetCurrentDir()
src  = Glob('*.c')
path = [cwd]

group = DefineGroup('NNOM mnist application', src, depend = ['USING_NNOM_MNIST_DEMOAPP'], CPPPATH = path)

Return('group')
