SRC_FILES := __fdopen.c __fmodeflags.c __lockfile.c __overflow.c 
SRC_FILES += __stdio_close.c __stdio_read.c __stdio_seek.c __stdio_write.c
SRC_FILES += __stdout_write.c __string_read.c 
SRC_FILES += __toread.c __towrite.c __uflow.c 
SRC_FILES += clearerr.c fclose.c feof.c fflush.c fgetc.c fgets.c fileno.c fopen.c fputc.c fputs.c fread.c fseek.c ftell.c fwrite.c 
SRC_FILES += ofl_add.c ofl.c perror.c remove.c rewind.c sprintf.c snprintf.c sscanf.c stderr.c stdin.c stdout.c printf.c puts.c putchar.c
SRC_FILES += ungetc.c vfprintf.c vfscanf.c vprintf.c vscanf.c vsnprintf.c vsprintf.c vsscanf.c stdio.c setvbuf.c



include $(KERNEL_ROOT)/compiler.mk