from building import *
import os

cwd = GetCurrentDir()

common = Split('''
tensorflow-lite-for-mcu/source/tensorflow/lite/micro/all_ops_resolver.cc
tensorflow-lite-for-mcu/source/tensorflow/lite/micro/debug_log.cc
tensorflow-lite-for-mcu/source/tensorflow/lite/micro/memory_helpers.cc
tensorflow-lite-for-mcu/source/tensorflow/lite/micro/micro_allocator.cc
tensorflow-lite-for-mcu/source/tensorflow/lite/micro/micro_error_reporter.cc
tensorflow-lite-for-mcu/source/tensorflow/lite/micro/micro_interpreter.cc
tensorflow-lite-for-mcu/source/tensorflow/lite/micro/micro_profiler.cc
tensorflow-lite-for-mcu/source/tensorflow/lite/micro/micro_string.cc
tensorflow-lite-for-mcu/source/tensorflow/lite/micro/micro_time.cc
tensorflow-lite-for-mcu/source/tensorflow/lite/micro/micro_utils.cc
tensorflow-lite-for-mcu/source/tensorflow/lite/micro/recording_micro_allocator.cc
tensorflow-lite-for-mcu/source/tensorflow/lite/micro/recording_simple_memory_allocator.cc
tensorflow-lite-for-mcu/source/tensorflow/lite/micro/simple_memory_allocator.cc
tensorflow-lite-for-mcu/source/tensorflow/lite/micro/test_helpers.cc
tensorflow-lite-for-mcu/source/tensorflow/lite/micro/benchmarks/keyword_scrambled_model_data.cc
tensorflow-lite-for-mcu/source/tensorflow/lite/micro/memory_planner/greedy_memory_planner.cc
tensorflow-lite-for-mcu/source/tensorflow/lite/micro/memory_planner/linear_memory_planner.cc
tensorflow-lite-for-mcu/source/tensorflow/lite/micro/testing/test_conv_model.cc
tensorflow-lite-for-mcu/source/tensorflow/lite/c/common.c
tensorflow-lite-for-mcu/source/tensorflow/lite/core/api/error_reporter.cc
tensorflow-lite-for-mcu/source/tensorflow/lite/core/api/flatbuffer_conversions.cc
tensorflow-lite-for-mcu/source/tensorflow/lite/core/api/op_resolver.cc
tensorflow-lite-for-mcu/source/tensorflow/lite/core/api/tensor_utils.cc
tensorflow-lite-for-mcu/source/tensorflow/lite/kernels/internal/quantization_util.cc
tensorflow-lite-for-mcu/source/tensorflow/lite/kernels/kernel_util.cc
tensorflow-lite-for-mcu/source/tensorflow/lite/schema/schema_utils.cc
tensorflow-lite-for-mcu/source/tensorflow/lite/micro/kernels/activations.cc
tensorflow-lite-for-mcu/source/tensorflow/lite/micro/kernels/arg_min_max.cc
tensorflow-lite-for-mcu/source/tensorflow/lite/micro/kernels/ceil.cc
tensorflow-lite-for-mcu/source/tensorflow/lite/micro/kernels/circular_buffer.cc
tensorflow-lite-for-mcu/source/tensorflow/lite/micro/kernels/comparisons.cc
tensorflow-lite-for-mcu/source/tensorflow/lite/micro/kernels/concatenation.cc
tensorflow-lite-for-mcu/source/tensorflow/lite/micro/kernels/conv_test_common.cc
tensorflow-lite-for-mcu/source/tensorflow/lite/micro/kernels/dequantize.cc
tensorflow-lite-for-mcu/source/tensorflow/lite/micro/kernels/detection_postprocess.cc
tensorflow-lite-for-mcu/source/tensorflow/lite/micro/kernels/elementwise.cc
tensorflow-lite-for-mcu/source/tensorflow/lite/micro/kernels/ethosu.cc
tensorflow-lite-for-mcu/source/tensorflow/lite/micro/kernels/flexbuffers_generated_data.cc
tensorflow-lite-for-mcu/source/tensorflow/lite/micro/kernels/floor.cc
tensorflow-lite-for-mcu/source/tensorflow/lite/micro/kernels/hard_swish.cc
tensorflow-lite-for-mcu/source/tensorflow/lite/micro/kernels/kernel_runner.cc
tensorflow-lite-for-mcu/source/tensorflow/lite/micro/kernels/kernel_util.cc
tensorflow-lite-for-mcu/source/tensorflow/lite/micro/kernels/l2norm.cc
tensorflow-lite-for-mcu/source/tensorflow/lite/micro/kernels/logical.cc
tensorflow-lite-for-mcu/source/tensorflow/lite/micro/kernels/logistic.cc
tensorflow-lite-for-mcu/source/tensorflow/lite/micro/kernels/maximum_minimum.cc
tensorflow-lite-for-mcu/source/tensorflow/lite/micro/kernels/neg.cc
tensorflow-lite-for-mcu/source/tensorflow/lite/micro/kernels/pack.cc
tensorflow-lite-for-mcu/source/tensorflow/lite/micro/kernels/pad.cc
tensorflow-lite-for-mcu/source/tensorflow/lite/micro/kernels/prelu.cc
tensorflow-lite-for-mcu/source/tensorflow/lite/micro/kernels/quantize.cc
tensorflow-lite-for-mcu/source/tensorflow/lite/micro/kernels/quantize_common.cc
tensorflow-lite-for-mcu/source/tensorflow/lite/micro/kernels/reduce.cc
tensorflow-lite-for-mcu/source/tensorflow/lite/micro/kernels/reshape.cc
tensorflow-lite-for-mcu/source/tensorflow/lite/micro/kernels/resize_nearest_neighbor.cc
tensorflow-lite-for-mcu/source/tensorflow/lite/micro/kernels/round.cc
tensorflow-lite-for-mcu/source/tensorflow/lite/micro/kernels/shape.cc
tensorflow-lite-for-mcu/source/tensorflow/lite/micro/kernels/split.cc
tensorflow-lite-for-mcu/source/tensorflow/lite/micro/kernels/split_v.cc
tensorflow-lite-for-mcu/source/tensorflow/lite/micro/kernels/strided_slice.cc
tensorflow-lite-for-mcu/source/tensorflow/lite/micro/kernels/sub.cc
tensorflow-lite-for-mcu/source/tensorflow/lite/micro/kernels/svdf_common.cc
tensorflow-lite-for-mcu/source/tensorflow/lite/micro/kernels/tanh.cc
tensorflow-lite-for-mcu/source/tensorflow/lite/micro/kernels/transpose_conv.cc
tensorflow-lite-for-mcu/source/tensorflow/lite/micro/kernels/unpack.cc
''')

app = Split('''
tensorflow-lite-for-mcu/source/tensorflow/lite/micro/examples/hello_world/main.cc
tensorflow-lite-for-mcu/source/tensorflow/lite/micro/examples/hello_world/main_functions.cc
tensorflow-lite-for-mcu/source/tensorflow/lite/micro/examples/hello_world/model.cc
tensorflow-lite-for-mcu/source/tensorflow/lite/micro/examples/hello_world/output_handler.cc
tensorflow-lite-for-mcu/source/tensorflow/lite/micro/examples/hello_world/constants.cc
''')

normal_ops = Split('''
tensorflow-lite-for-mcu/source/tensorflow/lite/micro/kernels/normal/add.cc
tensorflow-lite-for-mcu/source/tensorflow/lite/micro/kernels/normal/conv.cc
tensorflow-lite-for-mcu/source/tensorflow/lite/micro/kernels/normal/depthwise_conv.cc
tensorflow-lite-for-mcu/source/tensorflow/lite/micro/kernels/normal/fully_connected.cc
tensorflow-lite-for-mcu/source/tensorflow/lite/micro/kernels/normal/mul.cc
tensorflow-lite-for-mcu/source/tensorflow/lite/micro/kernels/normal/pooling.cc
tensorflow-lite-for-mcu/source/tensorflow/lite/micro/kernels/normal/softmax.cc
tensorflow-lite-for-mcu/source/tensorflow/lite/micro/kernels/normal/svdf.cc
''')

cmsis_ops = Split('''
tensorflow-lite-for-mcu/source/tensorflow/lite/micro/kernels/cmsis-nn/add.cc
tensorflow-lite-for-mcu/source/tensorflow/lite/micro/kernels/cmsis-nn/conv.cc
tensorflow-lite-for-mcu/source/tensorflow/lite/micro/kernels/cmsis-nn/depthwise_conv.cc
tensorflow-lite-for-mcu/source/tensorflow/lite/micro/kernels/cmsis-nn/fully_connected.cc
tensorflow-lite-for-mcu/source/tensorflow/lite/micro/kernels/cmsis-nn/mul.cc
tensorflow-lite-for-mcu/source/tensorflow/lite/micro/kernels/cmsis-nn/pooling.cc
tensorflow-lite-for-mcu/source/tensorflow/lite/micro/kernels/cmsis-nn/softmax.cc
tensorflow-lite-for-mcu/source/tensorflow/lite/micro/kernels/cmsis-nn/svdf.cc
''')

cmsis = Split('''
../cmsis_5/NN/Source/ActivationFunctions/arm_nn_activations_q15.c
../cmsis_5/NN/Source/ActivationFunctions/arm_nn_activations_q7.c
../cmsis_5/NN/Source/ActivationFunctions/arm_relu6_s8.c
../cmsis_5/NN/Source/ActivationFunctions/arm_relu_q15.c
../cmsis_5/NN/Source/ActivationFunctions/arm_relu_q7.c
../cmsis_5/NN/Source/BasicMathFunctions/arm_elementwise_add_s8.c
../cmsis_5/NN/Source/BasicMathFunctions/arm_elementwise_mul_s8.c
../cmsis_5/NN/Source/ConcatenationFunctions/arm_concatenation_s8_w.c
../cmsis_5/NN/Source/ConcatenationFunctions/arm_concatenation_s8_x.c
../cmsis_5/NN/Source/ConcatenationFunctions/arm_concatenation_s8_y.c
../cmsis_5/NN/Source/ConcatenationFunctions/arm_concatenation_s8_z.c
../cmsis_5/NN/Source/ConvolutionFunctions/arm_convolve_1_x_n_s8.c
../cmsis_5/NN/Source/ConvolutionFunctions/arm_convolve_1x1_HWC_q7_fast_nonsquare.c
../cmsis_5/NN/Source/ConvolutionFunctions/arm_convolve_1x1_s8_fast.c
../cmsis_5/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q15_basic.c
../cmsis_5/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q15_fast.c
../cmsis_5/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q15_fast_nonsquare.c
../cmsis_5/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q7_RGB.c
../cmsis_5/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q7_basic.c
../cmsis_5/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q7_basic_nonsquare.c
../cmsis_5/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q7_fast.c
../cmsis_5/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q7_fast_nonsquare.c
../cmsis_5/NN/Source/ConvolutionFunctions/arm_convolve_s8.c
../cmsis_5/NN/Source/ConvolutionFunctions/arm_convolve_wrapper_s8.c
../cmsis_5/NN/Source/ConvolutionFunctions/arm_depthwise_conv_3x3_s8.c
../cmsis_5/NN/Source/ConvolutionFunctions/arm_depthwise_conv_s8.c
../cmsis_5/NN/Source/ConvolutionFunctions/arm_depthwise_conv_s8_opt.c
../cmsis_5/NN/Source/ConvolutionFunctions/arm_depthwise_conv_u8_basic_ver1.c
../cmsis_5/NN/Source/ConvolutionFunctions/arm_depthwise_conv_wrapper_s8.c
../cmsis_5/NN/Source/ConvolutionFunctions/arm_depthwise_separable_conv_HWC_q7.c
../cmsis_5/NN/Source/ConvolutionFunctions/arm_depthwise_separable_conv_HWC_q7_nonsquare.c
../cmsis_5/NN/Source/ConvolutionFunctions/arm_nn_depthwise_conv_s8_core.c
../cmsis_5/NN/Source/ConvolutionFunctions/arm_nn_mat_mult_kernel_q7_q15.c
../cmsis_5/NN/Source/ConvolutionFunctions/arm_nn_mat_mult_kernel_q7_q15_reordered.c
../cmsis_5/NN/Source/ConvolutionFunctions/arm_nn_mat_mult_kernel_s8_s16.c
../cmsis_5/NN/Source/ConvolutionFunctions/arm_nn_mat_mult_kernel_s8_s16_reordered.c
../cmsis_5/NN/Source/ConvolutionFunctions/arm_nn_mat_mult_s8.c
../cmsis_5/NN/Source/FullyConnectedFunctions/arm_fully_connected_mat_q7_vec_q15.c
../cmsis_5/NN/Source/FullyConnectedFunctions/arm_fully_connected_mat_q7_vec_q15_opt.c
../cmsis_5/NN/Source/FullyConnectedFunctions/arm_fully_connected_q15.c
../cmsis_5/NN/Source/FullyConnectedFunctions/arm_fully_connected_q15_opt.c
../cmsis_5/NN/Source/FullyConnectedFunctions/arm_fully_connected_q7.c
../cmsis_5/NN/Source/FullyConnectedFunctions/arm_fully_connected_q7_opt.c
../cmsis_5/NN/Source/FullyConnectedFunctions/arm_fully_connected_s8.c
../cmsis_5/NN/Source/NNSupportFunctions/arm_nn_accumulate_q7_to_q15.c
../cmsis_5/NN/Source/NNSupportFunctions/arm_nn_add_q7.c
../cmsis_5/NN/Source/NNSupportFunctions/arm_nn_depthwise_conv_nt_t_padded_s8.c
../cmsis_5/NN/Source/NNSupportFunctions/arm_nn_depthwise_conv_nt_t_s8.c
../cmsis_5/NN/Source/NNSupportFunctions/arm_nn_mat_mul_core_1x_s8.c
../cmsis_5/NN/Source/NNSupportFunctions/arm_nn_mat_mul_core_4x_s8.c
../cmsis_5/NN/Source/NNSupportFunctions/arm_nn_mat_mult_nt_t_s8.c
../cmsis_5/NN/Source/NNSupportFunctions/arm_nn_mult_q15.c
../cmsis_5/NN/Source/NNSupportFunctions/arm_nn_mult_q7.c
../cmsis_5/NN/Source/NNSupportFunctions/arm_nn_vec_mat_mult_t_s8.c
../cmsis_5/NN/Source/NNSupportFunctions/arm_nntables.c
../cmsis_5/NN/Source/NNSupportFunctions/arm_q7_to_q15_no_shift.c
../cmsis_5/NN/Source/NNSupportFunctions/arm_q7_to_q15_reordered_no_shift.c
../cmsis_5/NN/Source/NNSupportFunctions/arm_q7_to_q15_reordered_with_offset.c
../cmsis_5/NN/Source/NNSupportFunctions/arm_q7_to_q15_with_offset.c
../cmsis_5/NN/Source/NNSupportFunctions/arm_nn_vec_mat_mult_t_svdf_s8.c
../cmsis_5/NN/Source/PoolingFunctions/arm_avgpool_s8.c
../cmsis_5/NN/Source/PoolingFunctions/arm_max_pool_s8.c
../cmsis_5/NN/Source/PoolingFunctions/arm_pool_q7_HWC.c
../cmsis_5/NN/Source/ReshapeFunctions/arm_reshape_s8.c
../cmsis_5/NN/Source/SVDFunctions/arm_svdf_s8.c
../cmsis_5/NN/Source/SoftmaxFunctions/arm_softmax_q15.c
../cmsis_5/NN/Source/SoftmaxFunctions/arm_softmax_q7.c
../cmsis_5/NN/Source/SoftmaxFunctions/arm_softmax_s8.c
../cmsis_5/NN/Source/SoftmaxFunctions/arm_softmax_u8.c
../cmsis_5/NN/Source/SoftmaxFunctions/arm_softmax_with_batch_q7.c
''')

CPPPATH = [
    os.path.join(cwd, 'tensorflow-lite-for-mcu/source'),
    os.path.join(cwd, 'tensorflow-lite-for-mcu/patch'),
    os.path.join(cwd, 'tensorflow-lite-for-mcu/source/third_party/gemmlowp'),
    os.path.join(cwd, 'tensorflow-lite-for-mcu/source/third_party/flatbuffers/include'),
    os.path.join(cwd, 'tensorflow-lite-for-mcu/source/third_party/ruy'),
    os.path.join(cwd, '../cmsis_5/'),
    os.path.join(cwd, '../cmsis_5/DSP/Include'),
    os.path.join(cwd, '../cmsis_5/NN/Include'),
    os.path.join(cwd, '../cmsis_5/Core/Include'),
    ]

# embedded C++ std don't have some math functions, use global math functions instead
CPPDEFINES = ['TF_LITE_USE_GLOBAL_CMATH_FUNCTIONS', 'TF_LITE_USE_GLOBAL_MAX', 'TF_LITE_USE_GLOBAL_MIN']
src = []

if GetDepend(['USING_TENSORFLOWLITEMICRO_NORMAL']):
    src += common + normal_ops
elif GetDepend(['USING_TENSORFLOWLITEMICRO_CMSISNN']):
    CPPDEFINES += ['CMSIS_NN']
    src += common + cmsis_ops + cmsis

if GetDepend(['USING_TENSORFLOWLITEMICRO_DEMOAPP']):
    src += app

# building scripts don't support building LIBRARY with LOCAL FLAGS(like LOCAL_CPPDEFINES) currently
# so LIBRARY use GLOBAL FLAGS(like CPPDEFINES)
#group = DefineGroup('tensorflow-lite-for-mcu', src, depend = ['USING_TENSORFLOWLITEMICRO'], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES, LIBRARY = True)
# static library link order matters, apps/mnist/main.o should be placed before libtensorflow.a, we should fix this later
group = DefineGroup('tensorflow-lite-for-mcu', src, depend = ['USING_TENSORFLOWLITEMICRO'], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

Return('group')
