/* Generated by mkromfs. Edit with caution. */
#include <rtthread.h>
#include <dfs_romfs.h>

#ifdef RT_USING_DFS_ROMFS
static const rt_uint8_t _romfs_root_hello_txt[] = {
0x58,0x49,0x55,0x4f,0x53,0x20,0x73,0x74,0x6d,0x33,0x32,0x68,0x37,0x20,0x52,0x6f,0x6d,0x46,0x53,0x20,0x73,0x75,0x63,0x63,0x65,0x73,0x73,0x21
};

static const struct romfs_dirent _romfs_root[] = {
    #ifdef BSP_USING_QSPI_FLASH
    {ROMFS_DIRENT_DIR, "FLASH", RT_NULL, 0},
    #endif
    #ifdef BSP_USING_SDMMC
    {ROMFS_DIRENT_DIR, "SD", RT_NULL, 0},
    #endif
    {ROMFS_DIRENT_FILE, "hello.txt", (rt_uint8_t *)_romfs_root_hello_txt, sizeof(_romfs_root_hello_txt)/sizeof(_romfs_root_hello_txt[0])}
};

const struct romfs_dirent romfs_root = {
    ROMFS_DIRENT_DIR, "/", (rt_uint8_t *)_romfs_root, sizeof(_romfs_root)/sizeof(_romfs_root[0])
};
#endif