ifeq ($(CONFIG_CONTROL_PROTOCOL_FINS), y)
	SRC_DIR := fins
endif

ifeq ($(CONFIG_CONTROL_PROTOCOL_MELSEC), y)
	SRC_DIR := melsec
endif

ifeq ($(CONFIG_CONTROL_PROTOCOL_OPCUA), y)
	SRC_DIR := opcua
endif

ifeq ($(CONFIG_CONTROL_PROTOCOL_S7), y)
	SRC_DIR := s7
endif

include $(KERNEL_ROOT)/compiler.mk
